# MIT License
#
# Copyright (c) 2024 Zerocracy
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
# This action doesn't test the current version of the code, which is in
# the 'master' branch or in the branch that you work with. Instead, it always
# tests agains the latest version released to the Docker Hub. It's not possible,
# as far as I understand, to change this behavior.
name: test
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - run: make install
      - run: |
          judges --verbose eval test.fb \
            "f = \$fb.insert; f.what = 'pmp'; f.area = 'hr';"
      # Pay attention: if this test fails, you can'f fix it in the "master"
      # branch, because it uses the "latest" version of the Docker image
      # already released to Docker Hub. In order to fix this test,
      # you should release a new version to Docker Hub and then try to fix
      # the test here. It's a two-steps process.
      - uses: ./
        with:
          verbose: true
          output: pages
          factbase: test.fb
